'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by SpecFlow (http://www.specflow.org/).
'     SpecFlow Version:1.9.0.77
'     SpecFlow Generator Version:1.9.0.0
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
#Region "Designer generated code"
'#pragma warning disable
Imports TechTalk.SpecFlow

Namespace LogicaDeAplicacion.UnitTests.ConfirmarPago
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77"),  _
     System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()>  _
    Partial Public Class CasosAlternosAlConfirmarUnPagoFeature
        
        Private Shared testRunner As TechTalk.SpecFlow.ITestRunner
        
#ExternalSource("Casos alternos al confirmar un pago.feature",1)
#End ExternalSource
        
        <Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()>  _
        Public Shared Sub FeatureSetup(ByVal testContext As Microsoft.VisualStudio.TestTools.UnitTesting.TestContext)
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner
            Dim featureInfo As TechTalk.SpecFlow.FeatureInfo = New TechTalk.SpecFlow.FeatureInfo(New System.Globalization.CultureInfo("es-ES"), "Casos alternos al confirmar un pago", "Se detalla las validaciones y acciones esperadas.", ProgrammingLanguage.VB, CType(Nothing,String()))
            testRunner.OnFeatureStart(featureInfo)
        End Sub
        
        <Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()>  _
        Public Shared Sub FeatureTearDown()
            testRunner.OnFeatureEnd
            testRunner = Nothing
        End Sub
        
        <Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()>  _
        Public Overridable Sub TestInitialize()
            If ((Not (TechTalk.SpecFlow.FeatureContext.Current) Is Nothing)  _
                        AndAlso (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title <> "Casos alternos al confirmar un pago")) Then
                LogicaDeAplicacion.UnitTests.ConfirmarPago.CasosAlternosAlConfirmarUnPagoFeature.FeatureSetup(Nothing)
            End If
        End Sub
        
        <Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()>  _
        Public Overridable Sub ScenarioTearDown()
            testRunner.OnScenarioEnd
        End Sub
        
        Public Overridable Sub ScenarioSetup(ByVal scenarioInfo As TechTalk.SpecFlow.ScenarioInfo)
            testRunner.OnScenarioStart(scenarioInfo)
        End Sub
        
        Public Overridable Sub ScenarioCleanup()
            testRunner.CollectScenarioErrors
        End Sub
        
        <Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(),  _
         Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Solo se confirmará pagos autorizados"),  _
         Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Casos alternos al confirmar un pago")>  _
        Public Overridable Sub SoloSeConfirmaraPagosAutorizados()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Solo se confirmará pagos autorizados", CType(Nothing,String()))
#ExternalSource("Casos alternos al confirmar un pago.feature",4)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
            Dim table1 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Propiedad", "Valor"})
            table1.AddRow(New String() {"Codigo de Referencia", "Ref2"})
            table1.AddRow(New String() {"Estado", "EnProceso"})
#ExternalSource("Casos alternos al confirmar un pago.feature",6)
testRunner.Given("una transaccion", CType(Nothing,String), table1, "Dada ")
#End ExternalSource
#ExternalSource("Casos alternos al confirmar un pago.feature",10)
testRunner.When("la transaccion ""Ref2"" se envia a confirmar", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Cuando ")
#End ExternalSource
#ExternalSource("Casos alternos al confirmar un pago.feature",11)
testRunner.Then("se registra en bitacora que solo se confirma transacciones autorizadas y no notif"& _ 
                    "icadas", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Entonces ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(),  _
         Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Se enviará una sola confirmación a la entidad destino"),  _
         Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Casos alternos al confirmar un pago")>  _
        Public Overridable Sub SeEnviaraUnaSolaConfirmacionALaEntidadDestino()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Se enviará una sola confirmación a la entidad destino", CType(Nothing,String()))
#ExternalSource("Casos alternos al confirmar un pago.feature",13)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
            Dim table2 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Propiedad", "Valor"})
            table2.AddRow(New String() {"Codigo de Referencia", "Ref2"})
            table2.AddRow(New String() {"Estado", "Autorizada"})
            table2.AddRow(New String() {"Se ha notificado", "True"})
#ExternalSource("Casos alternos al confirmar un pago.feature",15)
testRunner.Given("una transaccion", CType(Nothing,String), table2, "Dada ")
#End ExternalSource
#ExternalSource("Casos alternos al confirmar un pago.feature",20)
testRunner.And("la fecha actual es ""2015-06-01 12:00 PM""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Y ")
#End ExternalSource
#ExternalSource("Casos alternos al confirmar un pago.feature",21)
testRunner.When("la transaccion ""Ref2"" se envia a confirmar", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Cuando ")
#End ExternalSource
#ExternalSource("Casos alternos al confirmar un pago.feature",22)
testRunner.Then("se registra en bitacora que solo se confirma transacciones autorizadas y no notif"& _ 
                    "icadas", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Entonces ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(),  _
         Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Se reintentará si no hay comunicación con la entidad destino"),  _
         Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Casos alternos al confirmar un pago")>  _
        Public Overridable Sub SeReintentaraSiNoHayComunicacionConLaEntidadDestino()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Se reintentará si no hay comunicación con la entidad destino", CType(Nothing,String()))
#ExternalSource("Casos alternos al confirmar un pago.feature",24)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
            Dim table3 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Propiedad", "Valor"})
            table3.AddRow(New String() {"Codigo de referencia", "Ref1"})
            table3.AddRow(New String() {"Estado", "Autorizada"})
            table3.AddRow(New String() {"Se ha notificado", "False"})
            table3.AddRow(New String() {"Codigo de Entidad Origen", "401"})
            table3.AddRow(New String() {"Codigo de Entidad Destino", "501"})
            table3.AddRow(New String() {"Numero de Telefono Destino", "60607070"})
            table3.AddRow(New String() {"Codigo de Moneda Destino", "1"})
            table3.AddRow(New String() {"Fecha Valor", "2015-06-01 11:59 AM"})
#ExternalSource("Casos alternos al confirmar un pago.feature",26)
testRunner.Given("una transaccion", CType(Nothing,String), table3, "Dada ")
#End ExternalSource
            Dim table4 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Propiedad", "Valor"})
            table4.AddRow(New String() {"Url", "http://entidad501"})
            table4.AddRow(New String() {"TimeOut", "3000"})
            table4.AddRow(New String() {"Cn", "CnEntidad501"})
#ExternalSource("Casos alternos al confirmar un pago.feature",37)
testRunner.And("estos parametros de confirmacion de la entidad 501", CType(Nothing,String), table4, "Y ")
#End ExternalSource
            Dim table5 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Propiedad", "Valor"})
            table5.AddRow(New String() {"Cantidad maxima de intentos", "3"})
            table5.AddRow(New String() {"Intervalo de notificacion", "00:05:00"})
#ExternalSource("Casos alternos al confirmar un pago.feature",43)
testRunner.And("estos parametros de recalendarizacion", CType(Nothing,String), table5, "Y ")
#End ExternalSource
#ExternalSource("Casos alternos al confirmar un pago.feature",48)
testRunner.And("la fecha actual es ""2015-06-01 12:00 PM""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Y ")
#End ExternalSource
#ExternalSource("Casos alternos al confirmar un pago.feature",49)
testRunner.And("no se tiene comunicacion con la entidad destino", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Y ")
#End ExternalSource
#ExternalSource("Casos alternos al confirmar un pago.feature",51)
testRunner.When("la transaccion ""Ref1"" se envia a confirmar con 0 reintentos realizados", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Cuando ")
#End ExternalSource
            Dim table6 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Propiedad", "Valor"})
            table6.AddRow(New String() {"Codigo de Referencia", "Ref1"})
            table6.AddRow(New String() {"Codigo de Entidad Destino", "501"})
            table6.AddRow(New String() {"Url", "http://entidad501"})
            table6.AddRow(New String() {"TimeOut", "3000"})
            table6.AddRow(New String() {"Cn", "CnEntidad501"})
            table6.AddRow(New String() {"Fecha de Confirmacion", "2015-06-01 12:00 PM"})
#ExternalSource("Casos alternos al confirmar un pago.feature",53)
testRunner.Then("se generara esta confirmacion a la entidad destino", CType(Nothing,String), table6, "Entonces ")
#End ExternalSource
            Dim table7 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Propiedad", "Valor"})
            table7.AddRow(New String() {"Codigo de Referencia", "Ref1"})
            table7.AddRow(New String() {"Fecha de Inicio", "2015-06-01 12:05 PM"})
            table7.AddRow(New String() {"Numero de Reintento", "1"})
#ExternalSource("Casos alternos al confirmar un pago.feature",62)
testRunner.And("se recalendariza de esta manera", CType(Nothing,String), table7, "Y ")
#End ExternalSource
#ExternalSource("Casos alternos al confirmar un pago.feature",67)
testRunner.And("se registra la recalendarizacion en la bitacora", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Y ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(),  _
         Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("No se reintentará si no se puede invocar a la entidad por problemas de parámetros"& _ 
            ""),  _
         Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Casos alternos al confirmar un pago")>  _
        Public Overridable Sub NoSeReintentaraSiNoSePuedeInvocarALaEntidadPorProblemasDeParametros()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("No se reintentará si no se puede invocar a la entidad por problemas de parámetros"& _ 
                    "", CType(Nothing,String()))
#ExternalSource("Casos alternos al confirmar un pago.feature",69)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
            Dim table8 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Propiedad", "Valor"})
            table8.AddRow(New String() {"Codigo de referencia", "Ref1"})
            table8.AddRow(New String() {"Estado", "Autorizada"})
            table8.AddRow(New String() {"Se ha notificado", "False"})
            table8.AddRow(New String() {"Codigo de Entidad Origen", "401"})
            table8.AddRow(New String() {"Codigo de Entidad Destino", "501"})
            table8.AddRow(New String() {"Numero de Telefono Destino", "60607070"})
            table8.AddRow(New String() {"Codigo de Moneda Destino", "1"})
            table8.AddRow(New String() {"Fecha Valor", "2015-06-01 11:59 AM"})
#ExternalSource("Casos alternos al confirmar un pago.feature",70)
testRunner.Given("una transaccion", CType(Nothing,String), table8, "Dada ")
#End ExternalSource
            Dim table9 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Propiedad", "Valor"})
            table9.AddRow(New String() {"Url", ""})
            table9.AddRow(New String() {"TimeOut", "3000"})
            table9.AddRow(New String() {"Cn", "CnEntidad501"})
#ExternalSource("Casos alternos al confirmar un pago.feature",81)
testRunner.And("estos parametros de confirmacion de la entidad 501", CType(Nothing,String), table9, "Y ")
#End ExternalSource
#ExternalSource("Casos alternos al confirmar un pago.feature",87)
testRunner.When("la transaccion ""Ref1"" se envia a confirmar con 0 reintentos realizados", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Cuando ")
#End ExternalSource
#ExternalSource("Casos alternos al confirmar un pago.feature",89)
testRunner.Then("se registra en bitacora que no se puede invocar a la entidad por motivo de parame"& _ 
                    "tros invalidos", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Entonces ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
    End Class
End Namespace
'#pragma warning restore
#End Region
